### ISSUE TITLE
Error with Prisma v18.2: can't find schema.prisma

### ISSUE THREAD

**Issue by ephor** [prisma/prisma2#1134]
I updated Prisma version from 18.1 to 18.2, and then try to deploy Prisma to zeit/now and got an error. 

```
$ prisma2 generate
$ Error: Can't find schema.prisma
$ error Command failed with exit code 1.
```
The most interesting thing is that this is not a call of `prisma2 generate` from my package.json, but a call somewhere from a Prisma. 
Does Prisma has its own postinstall hook for `prisma2 generate`? Because it is called immediately after the dependencies of another package are installed.

**Comment by janpio** [comment]
Hey @ephor, thanks for your issue. Do you get this output during the deployment itself? Can you share more context, so we can understand what is triggering it?

**Comment by ephor** [comment]
```Downloading 63 deployment files...
Installing build runtime...
Build runtime installed: 579.839ms
Installing build runtime...
Looking up build cache...
Build runtime installed: 650.919ms
Looking up build cache...
Build cache found [238.64 kB, 908 files]
Build cache unpacked: 766.049ms
Installing dependencies...
yarn install v1.17.3
Build cache found [79.29 MB, 23609 files]
Build cache unpacked: 3174.690ms
[1/4] Resolving packages...
Installing dependencies...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/api > graphql-shield@5.7.3" has unmet peer dependency "graphql-middleware@^2.0.0 || ^3.0.0".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > @babel/plugin-proposal-nullish-coalescing-operator@7.7.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > @babel/plugin-proposal-optional-chaining@7.7.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > apollo-boost@0.4.4" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > next-with-apollo@4.3.0" has unmet peer dependency "prop-types@^15.6.2".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/api > graphql-yoga > graphql-playground-middleware-lambda@1.7.12" has unmet peer dependency "aws-lambda@^0.1.2".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/api > graphql-yoga > graphql-subscriptions@0.5.8" has incorrect peer dependency "graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > @babel/plugin-proposal-nullish-coalescing-operator > @babel/plugin-syntax-nullish-coalescing-operator@7.7.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > @babel/plugin-proposal-optional-chaining > @babel/plugin-syntax-optional-chaining@7.7.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > apollo-boost > apollo-cache-inmemory@1.6.3" has unmet peer dependency "graphql@0.11.7 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > apollo-boost > apollo-client@2.6.4" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > apollo-boost > apollo-link@1.2.13" has unmet peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > apollo-boost > apollo-link-http@1.5.16" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > apollo-boost > graphql-tag@2.10.1" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > next > native-url@0.2.3" has unmet peer dependency "@types/node@>=8.0.0".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/api > graphql-yoga > apollo-server-express > apollo-server-core@1.4.0" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > apollo-boost > apollo-link-error > apollo-link-http-common@0.2.15" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > react-apollo > @apollo/react-common@3.1.3" has unmet peer dependency "apollo-client@^2.6.4".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > react-apollo > @apollo/react-common@3.1.3" has unmet peer dependency "apollo-utilities@^1.3.2".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > react-apollo > @apollo/react-common@3.1.3" has unmet peer dependency "graphql@^14.3.1".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > react-apollo > @apollo/react-hooks@3.1.3" has unmet peer dependency "apollo-client@^2.6.4".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > react-apollo > @apollo/react-hooks@3.1.3" has unmet peer dependency "graphql@^14.3.1".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/api > graphql-yoga > apollo-server-express > apollo-server-core > apollo-cache-control@0.1.1" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/api > graphql-yoga > apollo-server-express > apollo-server-core > apollo-tracing@0.1.4" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/api > graphql-yoga > apollo-server-express > apollo-server-core > graphql-extensions@0.0.10" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > react-apollo@3.1.3" has unmet peer dependency "apollo-client@^2.6.4".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > react-apollo@3.1.3" has unmet peer dependency "graphql@^14.3.1".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > react-apollo > @apollo/react-components@3.1.3" has unmet peer dependency "apollo-cache@^1.3.2".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > react-apollo > @apollo/react-components@3.1.3" has unmet peer dependency "apollo-client@^2.6.4".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > react-apollo > @apollo/react-components@3.1.3" has unmet peer dependency "apollo-link@^1.2.12".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > react-apollo > @apollo/react-components@3.1.3" has unmet peer dependency "apollo-utilities@^1.3.2".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > react-apollo > @apollo/react-components@3.1.3" has unmet peer dependency "graphql@^14.3.1".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > react-apollo > @apollo/react-hoc@3.1.3" has unmet peer dependency "apollo-client@^2.6.4".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > react-apollo > @apollo/react-hoc@3.1.3" has unmet peer dependency "graphql@^14.3.1".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > react-apollo-hooks@0.5.0" has unmet peer dependency "apollo-client@^2.6.0".
warning "workspace-aggregator-f99d7ae8-a3d5-479f-98ba-7d5efc98be39 > @xxxxxx/web > react-apollo-hooks@0.5.0" has unmet peer dependency "graphql@*".
[4/4] Building fresh packages...
success Saved lockfile.
$ prisma2 generate
Error: Can't find schema.prisma
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Exited with 1
    at ChildProcess.child.on (/zeit/922cd6377aef4b37/.build-utils/.builder/node_modules/@now/next/dist/index.js:46408:24)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
worker exited with code 20 and signal null
yarn install v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/api > graphql-shield@5.7.3" has unmet peer dependency "graphql-middleware@^2.0.0 || ^3.0.0".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > @babel/plugin-proposal-nullish-coalescing-operator@7.7.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > @babel/plugin-proposal-optional-chaining@7.7.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > apollo-boost@0.4.4" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > next-with-apollo@4.3.0" has unmet peer dependency "prop-types@^15.6.2".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/api > graphql-yoga > graphql-playground-middleware-lambda@1.7.12" has unmet peer dependency "aws-lambda@^0.1.2".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/api > graphql-yoga > graphql-subscriptions@0.5.8" has incorrect peer dependency "graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > @babel/plugin-proposal-nullish-coalescing-operator > @babel/plugin-syntax-nullish-coalescing-operator@7.7.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > @babel/plugin-proposal-optional-chaining > @babel/plugin-syntax-optional-chaining@7.7.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > apollo-boost > apollo-cache-inmemory@1.6.3" has unmet peer dependency "graphql@0.11.7 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > apollo-boost > apollo-client@2.6.4" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > apollo-boost > apollo-link@1.2.13" has unmet peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > apollo-boost > apollo-link-http@1.5.16" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > apollo-boost > graphql-tag@2.10.1" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > next > native-url@0.2.3" has unmet peer dependency "@types/node@>=8.0.0".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/api > graphql-yoga > apollo-server-express > apollo-server-core@1.4.0" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > apollo-boost > apollo-link-error > apollo-link-http-common@0.2.15" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > react-apollo > @apollo/react-common@3.1.3" has unmet peer dependency "apollo-client@^2.6.4".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > react-apollo > @apollo/react-common@3.1.3" has unmet peer dependency "apollo-utilities@^1.3.2".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > react-apollo > @apollo/react-common@3.1.3" has unmet peer dependency "graphql@^14.3.1".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > react-apollo > @apollo/react-hooks@3.1.3" has unmet peer dependency "apollo-client@^2.6.4".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > react-apollo > @apollo/react-hooks@3.1.3" has unmet peer dependency "graphql@^14.3.1".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/api > graphql-yoga > apollo-server-express > apollo-server-core > apollo-cache-control@0.1.1" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/api > graphql-yoga > apollo-server-express > apollo-server-core > apollo-tracing@0.1.4" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/api > graphql-yoga > apollo-server-express > apollo-server-core > graphql-extensions@0.0.10" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > react-apollo@3.1.3" has unmet peer dependency "apollo-client@^2.6.4".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > react-apollo@3.1.3" has unmet peer dependency "graphql@^14.3.1".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > react-apollo > @apollo/react-components@3.1.3" has unmet peer dependency "apollo-cache@^1.3.2".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > react-apollo > @apollo/react-components@3.1.3" has unmet peer dependency "apollo-client@^2.6.4".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > react-apollo > @apollo/react-components@3.1.3" has unmet peer dependency "apollo-link@^1.2.12".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > react-apollo > @apollo/react-components@3.1.3" has unmet peer dependency "apollo-utilities@^1.3.2".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > react-apollo > @apollo/react-components@3.1.3" has unmet peer dependency "graphql@^14.3.1".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > react-apollo > @apollo/react-hoc@3.1.3" has unmet peer dependency "apollo-client@^2.6.4".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > react-apollo > @apollo/react-hoc@3.1.3" has unmet peer dependency "graphql@^14.3.1".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > react-apollo-hooks@0.5.0" has unmet peer dependency "apollo-client@^2.6.0".
warning "workspace-aggregator-8e330a2f-4a1e-4bbc-89b8-1ffb60292aec > @xxxxxx/web > react-apollo-hooks@0.5.0" has unmet peer dependency "graphql@*".
[4/4] Building fresh packages...
success Saved lockfile.
$ [ "$RUN_POSTINSTALL" = 'true' ] && yarn generate:safe && npm run migrate:safe && npm run seed:safe || exit 0
yarn run v1.17.3
$ [ "$RUN_GENERATE" = 'true' ] && yarn generate:prisma && yarn generate:nexus || exit 0
$ yarn run prisma2 generate --schema prisma/schema.prisma
$ /zeit/4f910dfe/node_modules/.bin/prisma2 generate --schema prisma/schema.prisma


Generating Photon.js to ./../../node_modules/@prisma/photon
Done in 6.29s

$ ts-node --transpile-only src/schema
Done in 9.54s.
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1576247419506-0.42899090107247306/node but npm is using /node10/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @xxxxxx/api@0.0.1 migrate:safe /zeit/4f910dfe/apps/api
> [ "$RUN_MIGRATIONS" = 'true' ] && yarn migrate || exit 0

yarn run v1.17.3
$ yarn run prisma2 lift up
$ /zeit/4f910dfe/node_modules/.bin/prisma2 lift up
🏋️‍ lift up

All migrations are already applied
Done in 4.59s.
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1576247419506-0.42899090107247306/node but npm is using /node10/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @xxxxxx/api@0.0.1 seed:safe /zeit/4f910dfe/apps/api
> [ "$RUN_SEEDS" = 'true' ] && yarn seed || exit 0

yarn run v1.17.3
$ ts-node prisma/seed
{ user1:
   { id: 'ck448gm1s0000rzrgchmhuwun',
     email: 'alice@prisma.io',
     password:
      '$2b$10$ZjONRZAxqX2pLoPax2xdcuzABTUEsFanQI6yBYCRtzpRiU4/X1uIu',
     name: 'Alice' },
  user2:
   { id: 'ck448gn1o0002rzrgigbyf0y6',
     email: 'bob@prisma.io',
     password:
      '$2b$10$o6KioO.taArzboM44Ig85O3ZFZYZpR3XD7mI8T29eP4znU/.xyJbW',
     name: 'Bob' } }
Done in 4.92s.
Done in 57.86s.
Using TypeScript 3.7.3 (local user-provided)
[31mError: apps/api/src/generated/nexus.ts(13,11): error TS2304: Cannot find name 'NexusPrisma'.
apps/api/src/generated/nexus.ts(14,12): error TS2304: Cannot find name 'NexusPrisma'.
[0m
Build completed. Populating build cache...
Build cache uploaded [79.28 MB]: 1407.844ms
done
done```

**Comment by pantharshit00** [comment]
Looks like you are using yarn workspaces. Can you please tell me whether prisma2 is installed in the root or it is installed as a dependency of a subpackage

We need to test the monorepo deployment setup with zeit and prisma2.

**Comment by brobertsUPS** [comment]
@pantharshit00 I ran into the same issue and am also using yarn workspaces and building on zeit/now. For me, `prisma2` was installed in the root. I will try to see if using the `nohoist` option from workspaces fixes the issue.

**Comment by ephor** [comment]
> Can you please tell me whether prisma2 is installed in the root or it is installed as a dependency of a subpackage

it is installed as a dependency of a subpackage

**Comment by momakes** [comment]
How to fix this?

**Comment by dimitarnestorov** [comment]
I've added the following to `now.json` and seems to be working with `2.0.0-preview019`:
```json
{
  "build": {
    "env": {
      "NOW_BUILDER": ""
    }
  }
}
```

**Comment by pantharshit00** [comment]
Hi,

I tried reproducing this but I was unable to do so. I was successfully able to deploy and it is working fine: https://prisma2-yarn-monorepo.now.sh/

Here is the code that I used: https://github.com/harshit-test-org/prisma2-zeit-now-yarn-workspace

I didn't used the above workaround. So someone can please point me to a working reproduction of this.

**Comment by dimitarnestorov** [comment]
Here's a minimal reproduction repo:
https://github.com/dimitarnestorov/next-prisma-monorepo
![image](https://user-images.githubusercontent.com/8790386/71994853-251b5500-3242-11ea-8a4e-9badc0208f2c.png)

**Comment by pantharshit00** [comment]
I looked at your reproduction, you are executing the generate command with frontend as cwd:
```
// packages/frontend/package.json
"scripts": {
    "dev": "next",
    "build": "yarn workspace backend generate && next build",
    "start": "next start"
  },
```


Our CLI tries to resolve schema.prisma from cwd, when this command is executed, it tries to look for schema file in frontend directory. Instead, run this from the backend folder instead.

**Comment by dimitarnestorov** [comment]
Ah yes, you're using `process.env.INIT_CWD`. What's your opinion on switching to `process.cwd()`?
![image](https://user-images.githubusercontent.com/8790386/72106300-cafcbb80-3337-11ea-835e-a13f98da5dc2.png)

**Comment by momakes** [comment]
@pantharshit00 I will send you a repro tomorrow.

**Comment by pantharshit00** [comment]
> Ah yes, you're using process.env.INIT_CWD. What's your opinion on switching to process.cwd()?

We actually try to resolve using `process.cwd()` giving it the first preference. Looks like now handles the command execution differently so these values are assigned different there.

Source code of our resolution logic:
https://github.com/prisma/prisma2/blob/d81ff142fcef145cde896ac9e914cfe43089ecc0/cli/cli/src/getSchema.ts#L14


>  I will send you a repro tomorrow.
Thanks @momakes :)

**Comment by dimitarnestorov** [comment]
Alright, dialed it back a notch.
I just added a postinstall script on the backend to run `prisma2 generate` and got the same issue. Updated https://github.com/dimitarnestorov/next-prisma-monorepo

![image](https://user-images.githubusercontent.com/8790386/72126177-dec61300-3373-11ea-9eb7-19263355d1b0.png)

**Comment by momakes** [comment]
https://github.com/momakes/prisma0182-monorepo-bug

**Comment by pantharshit00** [comment]
Ok, I can confirm this bug now. I was reproducing this and wasn't able to remove the postinstall hook no matter what. Then I checked the code and sure enough we were mutating the package.json when `NOW_BUILDER` is set. So I talked internally on why we are doing this and explanantion is as following:

Now caches the node_modules folder. Then on every deploy they reexecute yarn install. If there was no change in the package.json, the posinstall hook of Photon doesn’t get reexecuted. Therefore, if we are in a Now environment, we add prisma2 generate to the postinstall hook of the users main package.json to fix this behavior. We also created an issue in yarn to track this: https://github.com/yarnpkg/yarn/issues/7762

We should just make this thing fail silently and fix this workspace bug. For now you can opt out of this behaviour by setting `NOW_BUILDER` to `""` as pointed out by @dimitarnestorov above. Thanks everyone for having patience on this 🙌

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
